#url: "http://127.0.0.1:4000" # the base hostname & protocol for your site, e.g. http://example.com
#url: "https://cryptwright.github.io" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://www.cryptwright.com"
# baseurl: "/" # the subpath of your site, e.g. /blog
title: "Chris Valentine" # the name of your site, e.g. ACME Corp.
mailchimp-list: "https://cryptwright.us14.list-manage.com/subscribe/post?u=1d49a65aa22e2f77f797b25e3&amp;id=6c99a12a1b"
sass:
  sass_dir: _sass

collections:
  releases:
  production:
  vtt_releases:

exclude:
  - Rakefile

## Design Notes
## After realizing I was adding too much too soon i'm removing the blog, product details, and mailing list until later.
## Their efforts are still here just hidden until time to use.
## 
## pushing to github pages
## ------------------------
## https://stackoverflow.com/questions/17835937/how-do-i-push-jekyll-site-directory-to-gh-pages-branch-and-leave-the-source-in